//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by wyyt.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WYYT_DIALOG                 102
#define IDS_ERR_CREATE_DIR              102
#define IDS_INIT_DIR_SYS_ATTACHENTS     103
#define IDS_INIT_DIR_TEMP               104
#define IDS_ABORT                       105
#define IDS_CANCEL                      106
#define IDS_CONTINUE                    107
#define IDS_DONOTASKAGAIN               108
#define IDS_DONOTTELLAGAIN              109
#define IDS_DONOTSHOWAGAIN              110
#define IDS_IGNORE                      111
#define IDS_IGNOREALL                   112
#define IDS_NO                          113
#define IDS_NOTOALL                     114
#define IDS_TREEOPTIONS_OK              115
#define IDS_RETRY                       116
#define IDS_SKIP                        117
#define IDS_SKIPALL                     118
#define IDS_TRYAGAIN                    119
#define IDS_MB_YES                      120
#define IDS_YESTOALL                    121
#define IDS_INIT_DIR_CONFIG             122
#define IDS_INIT_DIRS                   123
#define IDS_MB_LANGUAGEINFO             124
#define IDS_MAIN_BTN_CONNECT            125
#define IDS_YT_SYSRES                   126
#define IDS_YT_GROUPRES                 127
#define IDR_MAINFRAME                   128
#define IDS_YT_PRIVATERES               128
#define IDS_EM_SEARCH                   129
#define IDS_EM_FILES                    130
#define IDS_EM_MESSAGES                 131
#define IDS_IRC                         132
#define IDS_EM_STATISTIC                133
#define IDS_EM_PREFS                    134
#define IDS_TOOLS                       135
#define IDS_EM_HELP                     136
#define IDS_SELECTTOOLBARBITMAPDIR      137
#define IDS_LOADFILTER_EMTOOLBAR        138
#define IDS_SELSKINPROFILEDIR           139
#define IDS_LOADFILTER_EMSKINFILES      140
#define IDS_SELECTTOOLBARBITMAP         141
#define IDS_DEFAULT                     142
#define IDS_NOTEXTLABELS                143
#define IDD_DIALOG_SYS_RES_MANAGE       143
#define IDS_ENABLETEXTLABELS            144
#define IDD_DIALOG_GROUP_RES_MANAGER    144
#define IDS_TEXTLABELSONRIGHT           145
#define IDD_DIALOG_PRI_RES_MANAGE       145
#define IDS_LARGEICONS                  146
#define IDD_DIALOG_ARCHPREV             146
#define IDS_SEL_SKIN                    147
#define IDI_ICON1                       147
#define IDS_SEL_SKINDIR                 148
#define IDI_ICON_IHAS                   148
#define IDS_SMALLICONS                  149
#define IDS_TOOLBARSKINS                150
#define IDS_SKIN_PROF                   151
#define IDS_TEXTLABELS                  152
#define IDD_DIALOG_PPG_GENERAL          152
#define IDS_CUSTOMIZETOOLBAR            153
#define IDD_DIALOG_SYSRES_SEARCH        153
#define IDS_SEARCH_ANY                  154
#define IDB_DOWN2X                      154
#define IDS_SHAREDFOLDERS               155
#define IDB_DOWN                        155
#define IDS_VIEW1                       156
#define IDB_UP2X                        156
#define IDS_VIEW2                       157
#define IDB_UP                          157
#define IDS_CONTENT_INFO                158
#define IDS_PW_APPLY                    159
#define IDS_PW_TRAY                     160
#define IDS_READONLY                    161
#define IDS_PW_GENERAL                  162
#define IDR_LISTVIEW                    162
#define IDS_PW_LANG                     163
#define IDS_DL_RECORD_TITLE             164
#define IDS_DL_RECORD_SIZE              165
#define IDS_RECORD_SUMMARY              166
#define IDS_SYS_RESOURCES               167
#define IDS_SAVE_AS                     168
#define IDS_SHOW_ALTER_VERSION          169
#define IDS_SHOW_COMMENT                170
#define IDD_DLG_ADDMOD_CLASSINFO        170
#define IDS_DETAILS                     171
#define IDS_ALLCLASSINFOS               172
#define IDS_CLASSINFOOPERATOR           173
#define IDS_ADD_PARENTCLASS             174
#define IDS_ADD_SONCLASS                175
#define IDS_MOD_CLASSINFO               176
#define IDS_DEL_CLASSINFO               177
#define IDS_ADD_CLASSINFO_PROMPT        178
#define IDD_DLG_REC_PP_CLASS            178
#define IDS_STATIC_CLASSINFO_NEWNAME    179
#define IDS_TITLE_ADDCLASSINFO          180
#define IDD_DIALOG_RECORD_DETAILS       180
#define IDS_TITLE_MODCLASSINFO          181
#define IDD_DIALOG_RECORD_DETAILS_CLASS 181
#define IDS_DEL_CLASSINFO_PROMPT        182
#define IDS_DEL_SYSCLASSINFO_PROMPT     183
#define IDD_DIALOG_RECORD_DETAILS_CONTENT 183
#define IDS_FLAG_CLASSINFO_RECOMMEND    184
#define IDD_DIALOG_RECORD_DETAILS_ATTACH 184
#define IDS_FLAG_CLASSINFO_RECOMMEND_CANCLE 185
#define IDS_SYS_NOTESCLASSINFOS         186
#define IDD_DIALOG_RECORD_DETAILS_ATTACH_ADD 186
#define IDS_KBYTESPERSEC                187
#define IDD_DIALOG_ATTACHS              187
#define IDS_BYTESPERSEC                 188
#define IDS_BYTES                       189
#define IDS_MBYTESPERSEC                190
#define IDS_GBYTESPERSEC                191
#define IDS_TBYTESPERSEC                192
#define IDS_KBYTES                      193
#define IDS_MBYTES                      194
#define IDS_GBYTES                      195
#define IDS_TBYTES                      196
#define IDS_SRM_RELOAD                  197
#define IDS_ADDRECORD                   198
#define IDS_MODRECORD                   199
#define IDS_DELRECORD                   200
#define IDS_SHOWRECORD                  201
#define IDS_RECORD_OPERTYPE_CLASS       202
#define IDS_RECORD_OPERTYPE_CONTENT     203
#define IDS_PROP_INFO_TITLE             204
#define IDS_PROP_INFO_KEY               205
#define IDS_PROP_INFO_CONTENT           206
#define IDS_PROP_INFO_REF               207
#define IDS_CLASSINFOSEL                208
#define IDS_FLAG_RECORD_MAINCLASS       209
#define IDS_FLAG_RECORD_MAINCLASS_CANCLE 210
#define IDS_PROP_INFO_SUCCESS           211
#define IDS_PROP_INFO_FIRST_CANCEL_MAINCLASS 212
#define IDS_LOGENTRY                    213
#define IDS_COPY                        214
#define IDS_SELECTALL                   215
#define IDS_PW_RESET                    216
#define IDS_SAVELOG                     217
#define IDS_AUTOSCROLL                  218
#define IDS_PROP_INFO_FIRST_SEL_MAINCLASS 219
#define IDS_PROP_INFO_FIRST_MAINCLASS   220
#define IDS_PROP_INFO_CLASSES           221
#define IDS_SEL_SYSCLASSINFO_PROMPT     222
#define IDS_PROP_SELBYCTL               223
#define IDS_PROP_INFO_SEL_MAXCOUNTS     224
#define IDS_PROP_INFO_SEL_MAINMUST      225
#define IDS_PROP_INFO_TITLE_NULL        226
#define IDS_CONFIRM_RECORDDELETE        227
#define IDS_DL_RECORD_SID               228
#define IDS_DL_RECORD_MODTIME           229
#define IDS_DL_RECORD_INPUTTIME         230
#define IDS_RECORD_OPERTYPE_ATTACH      231
#define IDS_CODE                        232
#define IDS_FILENAME                    233
#define IDS_FILESIZE                    234
#define IDS_FILESTATUS                  235
#define IDS_ADD                         236
#define IDS_DEL                         237
#define IDS_FS_UNDOWNED                 238
#define IDS_FS_DOWNED                   239
#define IDS_STATIC_CODEID               240
#define IDS_OK                          241
#define IDS_ATTACH_ADD                  242
#define IDS_STATIC_FULLNAME_SAVE        243
#define IDS_ALARM_MAXATTACH             244
#define IDS_STATIC_SELECTUPFILE         245
#define IDS_UNDO                        246
#define IDS_CUT                         247
#define IDS_PASTE                       248
#define IDS_DELETESELECTED              249
#define IDS_FSTAT_WAITING               250
#define IDS_ATTACH                      251
#define IDS_OPEN_FILE                   252
#define IDS_FILE_SAVEAS                 253
#define IDS_RICH_UNDO                   254
#define IDS_RICH_CUT                    255
#define IDD_DIALOG_TEST                 255
#define IDS_RICH_COPY                   256
#define IDD_DIALOG_PPG_DIRS             256
#define IDS_RICH_PASTE                  257
#define IDS_RICH_CLEAR                  258
#define IDS_RICH_SELECTALL              259
#define IDD_PPG_SECURITY                259
#define IDS_RICH_SETFONT                260
#define IDS_PW_DIRSET                   261
#define IDD_DIALOG_LOGIN_PRI            261
#define IDS_SELECT_SYSATTACHDIR         262
#define IDS_SELECT_PRIATTACHDIR         263
#define IDD_WYYTTRAYDLG                 263
#define IDS_SECURITY                    264
#define IDS_PRI_PWD_ENABLE              265
#define IDS_PRI_USERNAME                266
#define IDI_ICON2                       266
#define IDS_PRI_PWD                     267
#define IDD_DIALOG_DONATE               267
#define IDS_PASSCHECK                   268
#define IDS_PROP_USERPWD_EMPTY          269
#define IDS_ABOUT_INFOS                 270
#define IDS_HOTMENU                     271
#define IDS_HM_LINKHP                   272
#define IDS_HM_LINKFAQ                  273
#define IDS_HM_LINKVC                   274
#define IDS_WEBSVEDIT                   275
#define IDS_CONSTRUCTION                276
#define IDS_LINKS                       277
#define IDS_CLOSEWYYT                   278
#define IDS_MAIN_EXIT                   279
#define IDS_PW_PROMPT                   280
#define IDS_INFOS                       281
#define IDS_MAIN_POPUP_RESTORE          282
#define IDS_EXIT                        283
#define IDS_FILE_MOD                    284
#define IDS_STATIC_INFO                 285
#define IDS_ATTACH_OPENFOLDER           286
#define IDS_ATTACH_SHOW                 287
#define IDS_STATIC_FILENAME             288
#define IDS_PROP_INFO_CONTENTTOOLENGTH  289
#define IDS_INFO_VERSIONS               290
#define IDS_DONATEDE                    291
#define IDC_HOTMENU                     1000
#define IDC_STATUSBAR                   1001
#define IDC_SRM_FILTER                  1002
#define IDC_SRM_CLASSINFOTREE           1003
#define IDC_SRM_RECORDLIST              1004
#define IDC_SRM_RECORD_FILTER           1005
#define IDC_BTN_HIDESHOWDETAILS         1006
#define IDC_LANGS                       1008
#define IDC_LANG_FRM                    1009
#define IDC_RELOADSCLASSINFOS           1010
#define IDC_STATIC_NEWCLASSNAME         1011
#define IDC_EDIT_NEWCLASSNAME           1012
#define IDC_LIST_OPER_OPTION            1013
#define IDC_STATIC_FRAME_INFO           1014
#define IDC_TREE_CLASSES                1015
#define IDC_EDIT_TITLE                  1016
#define IDC_EDIT_KEY                    1017
#define IDC_EDIT_CONTENT                1018
#define IDC_EDIT_REF                    1019
#define IDC_STATIC_TITLE                1020
#define IDC_STATIC_KEY                  1021
#define IDC_STATIC_CONTENT              1022
#define IDC_STATIC_REF                  1023
#define IDC_STATIC_CLASSES              1024
#define IDC_RICHEDIT2_SELCLASSINFO      1025
#define IDC_STATIC_PROPINFO             1025
#define IDC_STATIC_PROP_CLASSSEL        1026
#define IDC_LIST_ATTACHS                1027
#define IDC_BUTTON_ADD                  1028
#define IDC_BUTTON_DEL                  1029
#define IDC_STATIC_FULLNAME_UP          1030
#define IDC_EDIT_FULLNAME_UP            1031
#define IDC_STATIC_DOWNADDRESS          1032
#define IDS_STATIC_DOWNADDRESS          1032
#define IDC_STATIC_DOWNADRESS           1032
#define IDC_EDIT_DOWNADDRESS            1033
#define IDS_STATIC_FULLNAME_UP          1033
#define IDC_STATIC_CODEID               1034
#define IDC_STATIC_SELECTUPFILE         1034
#define IDC_EDIT_CODEID                 1035
#define IDC_EDIT_UPFILE                 1035
#define IDC_BUTTON_BROWSEV              1036
#define IDC_STATIC_FULLNAME_SAVE        1036
#define IDC_EDIT_FULLNAME_SAVE          1037
#define IDC_RICHEDIT2_CONTENT           1037
#define IDC_RICHEDIT2_NR                1038
#define IDC_EDIT_TEST                   1041
#define IDC_EDIT1                       1042
#define IDC_PRI_RECORD_FILTER           1042
#define IDC_EDIT_SYSATTACHPATH          1042
#define IDC_EDIT_PWD                    1042
#define IDC_EDIT_USERNAME_CHECK         1042
#define IDC_EDIT_INFO                   1042
#define IDC_EDIT_VERSION                1042
#define IDC_EDIT_BANK                   1042
#define IDC_PRM_CLASSINFOTREE           1043
#define IDC_EDIT_PRIATTACHPATH          1043
#define IDC_EDIT_USERNAME               1043
#define IDC_STATIC_PROP_CLASSSEL_PRI    1044
#define IDC_PRM_RECORDLIST              1045
#define IDC_BTN_HIDESHOWDETAILS_PRI     1046
#define IDC_PRM_FILTER                  1047
#define IDC_STATIC_SYSATTACHPATH        1048
#define IDC_BUTTON_SYSATTACHSEL         1049
#define IDC_STATIC_PRIATTACHPATH        1050
#define IDC_CHECK_PRI_PWD_ENABLE        1050
#define IDC_BUTTON_PRIATTACHSEL         1051
#define IDC_STATIC_USERNAME             1051
#define IDC_STATIC_PWD                  1052
#define IDC_STATIC_SHOW_USERPWD         1052
#define IDC_EDIT_USERPWD_CHECK          1053
#define IDC_STATIC_SHOW_USERNAME        1054
#define IDC_EXIT                        1055
#define IDC_SIDEBAR                     1056
#define IDC_TRAY_EXIT                   1057
#define IDC_RESTORE                     1058
#define IDC_STATIC_INFO                 1058
#define IDC_PREFERENCES                 1059
#define IDC_EDIT_FILENAME               1059
#define IDC_ABOUT                       1060
#define IDC_STATIC_FILENAME             1060
#define IDC_BUTTON_VERINFO              1061
#define IDC_BUTTON1                     1062
#define IDC_BUTTON_UPSYSDATA            1062
#define IDC_SPLITTER_SYSRESMANAGE       2889
#define IDA_ENTER                       32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        268
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
